### ISSUE TITLE
Crown Image in footer is hard coded

### ISSUE THREAD

**Issue by craig-shenton** [craig-shenton/govuk_mkdocs#7]
Could not get relative paths working in css

https://github.com/craig-shenton/govuk_mkdocs/blob/f913a8141666eed86d8885865337d6bfe14d6b1b/docs/assets/stylesheets/extra.css#L102C1-L113C2

```css
.md-copyright a.gocuk-crest {
  text-align: center;
  display: inline-block;
  min-width: 125px;
  padding-top: 112px;
  background-image: url(https://craig-shenton.github.io/govuk_mkdocs/assets/images/govuk-crest.svg);
  background-repeat: no-repeat;
  background-position: 50% 0%;
  background-size: 125px 102px;
  text-align: center;
  white-space: nowrap;
}
```
